---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: validar conexion a apache
      block:
        - name: comprobamos la url
          uri:
            url: "http://{{ hosts }}"
      rescue:
        - name: levantamos apache
          service:
            name: httpd
            state: started
      always:
        - name: ejecutamos siempre consulta url
          uri:
            url: "http://{{ hosts }}"